name: 'Translate'
description: 'Automatic translation using GPT'

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - main
      - 'branch*'

inputs:
  folder-to-translate:  # id of input
    description: 'Path to folder to translate'
    required: true
    default: 'docs/en/'
  language:  # id of input
    description: 'Language to translate to'
    required: true
    default: 'zh'
  output-folder:
    description: "Output Folder"
    default: 'docs/zh/'
  max-chunk-tokens:
    description: "Max size of chunk to translate at once"
    default: "1000"
  config-folder:
    description: "Config Folder"
    default: './docs/docusaurus/translate/configs'
outputs:
  translated-files:
    description: 'Translated files'
    value: ${{ steps.changed-files.outputs.changed_files }} 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * SUN'  # once a week on Sunday
permissions:
  contents: read
  issues: write

jobs:
  grab_feedback_from_posthog:
    name: Pull feedback using API
    runs-on: ubuntu-latest
    env:
      POSTHOG_TOKEN: ${{ secrets.POSTHOG_PERSONAL_API_KEY }}
      ALGOLIA_TOKEN: ${{ secrets.ALGOLIA_ANALYTICS_KEY }}

    steps:
      - name: Get changed files
        id: changed-files
        run: |
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep '\.md$|\.mdx$' | xargs)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gpt-translate
        shell: bash
      - name: translating files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ALGOLIA_TOKEN: ${{ secrets.ALGOLIA_ANALYTICS_KEY }}
        run: |
          gpt_translate.files ${{ steps.changed-files.outputs.changed_files }} \
            --input_folder ${{ inputs.folder-to-translate }} \
            --out_folder ${{ inputs.output-folder }} \
            --language ${{ inputs.language }} \
            --max_chunk_tokens ${{ inputs.max-chunk-tokens }} \
            --config_folder ${{ inputs.config-folder }} \
            --replace
        shell: bash
