name: 'Translate'

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - main
      - 'branch*'

permissions:
  contents: read
  issues: write

outputs:
  translated-files:
    description: 'Translated files'
    value: ${{ steps.changed-files.outputs.changed_files }} 

jobs:
  grab_feedback_from_posthog:
    name: Pull feedback using API
    runs-on: ubuntu-latest
    env:
      POSTHOG_TOKEN: ${{ secrets.POSTHOG_PERSONAL_API_KEY }}
      ALGOLIA_TOKEN: ${{ secrets.ALGOLIA_ANALYTICS_KEY }}

    steps:
      - name: Get changed files
        id: changed-files
        run: |
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep '\.md$|\.mdx$' | xargs)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gpt-translate
        shell: bash
      - name: translating files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ALGOLIA_TOKEN: ${{ secrets.ALGOLIA_ANALYTICS_KEY }}
        run: |
          gpt_translate.files ${{ steps.changed-files.outputs.changed_files }} \
            --input_folder docs/en \
            --out_folder docs/zh \
            --language zh \
            --config_folder docs/docusaurus/translate/configs \
            --replace
        shell: bash
