name: 'Translate'

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - main
      - 'branch*'

permissions:
  contents: read
  issues: write

jobs:
  grab_feedback_from_posthog:
    name: Pull feedback using API
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.changed-files.outputs.changed_files }}

    steps:
      - uses: actions/checkout@v4

      - name: Fetch changed file names
        id: changed-files
        run: |
            echo "changed_files=$(git diff --diff-filter=d --name-only HEAD^1 HEAD | grep '\.md$|\.mdx$' | xargs)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gpt-translate
          python -m pip install -r docs/docusaurus/translation/requirements.txt
        shell: bash
      - name: translating files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        shell: bash
        working-directory: docs/docusaurus/translation
        run: |
          gpt_translate.files ${{ steps.changed-files.outputs.changed_files }} \
            --out_folder docs/zh \
            --language zh \
            --config_path docs/docusaurus/translation/configs/config.yaml \
            --replace
